version: '4'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - '5432:5432'
    volumes:
      - progresDB:/var/lib/postgresql/data
    env_file:
      - ./.env
    restart: always  # Ensures it restarts if it crashes

  pgAdmin:
    image: dpage/pgadmin4
    container_name: pgAdmin
    env_file:
      - ./.env
    ports:
      - '5050:80'
    restart: always

  web-service:
    build: .
    container_name: web-service
    env_file:
      - ./.env
    deploy:
      replicas: 3  # Runs 3 instances for redundancy
      restart_policy:
        condition: on-failure
    ports:
      - "8000:8000"
    networks:
      - backend-network

networks:
  backend-network:

volumes:
  progresDB:
