name: Deploy Web-Service & Triple-ts-mediclinic

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: SSH into VPS & Deploy
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        passphrase: ${{ secrets.VPS_SSH_KEY_PASSPHRASE }} 
        script: |
          # Pull latest code
          cd ~/Triple-ts-mediclinic
          git pull git@github.com:imrany/Triple-mediclinic.git main

          # Stop & remove existing containers
          sudo docker stop web-service || true
          sudo docker rm web-service || true

          # Remove old image
          sudo docker rmi web-service || true

          # Build new image
          cd ~/Triple-ts-mediclinic/web-service
          
          # Rebuild images and deploy multiple containers
          sudo docker-compose up -d --scale web-service=3 --build

          # Ensure Node.js & npm exist before frontend build
          if ! command -v npm &> /dev/null; then
            sudo apt update
            sudo apt install nodejs npm -y
          fi

          # Deploy React frontend
          cd ~/Triple-ts-mediclinic/client
          npm install
          npm run build
          sudo rm -rf /var/www/triple-ts-mediclinic
          sudo mv dist /var/www/triple-ts-mediclinic

          # Restart Nginx safely
          sudo systemctl restart nginx || sudo nginx -t
